# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-20 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='our_database',
            old_name='password',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='our_database',
            old_name='username',
            new_name='url',
        ),
    ]
