# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-11 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get', '0002_auto_20170220_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_database',
            name='prev_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='our_database',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
