# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-25 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get', '0003_auto_20170311_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_id', models.CharField(max_length=5)),
                ('url', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='our_database',
            name='prev_url',
        ),
        migrations.RemoveField(
            model_name='our_database',
            name='time',
        ),
    ]
